name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for gh-deploy to work properly
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-material[imaging]
          pip list  # Show all installed packages
      
      - name: Debug - Check directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files in root:"
          ls -la
          echo "Checking docs folder:"
          ls -la docs/ || echo "docs folder not found"
          echo "Checking blog structure:"
          ls -la docs/blog/ || echo "docs/blog not found"
          ls -la docs/blog/posts/ || echo "docs/blog/posts not found"
      
      - name: Test build locally first
        run: mkdocs build --verbose
      
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --verbose